logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor: trace
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zoomania?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    #        The DB will be instasiate first before inserst
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  # For uploading files to our server
  servlet:
    multipart:
      max-file-size: 12MB
      max-request-size: 5MB
  mvc:
    # For PUT, PATCH and DELTE on forms
    hiddenmethod:
      filter:
        enabled: true